package com.ak.entity;
// Generated 2016-1-2 17:35:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ILoginfo generated by hbm2java
 */
@Entity
@Table(name = "i_loginfo", catalog = "akdbs")
public class ILoginfo implements java.io.Serializable {

	private Integer did;
	private Integer useDid;
	private String logip;
	private Date lastuse;
	private String client;
	private int orgDid;

	public ILoginfo() {
	}

	public ILoginfo(int orgDid) {
		this.orgDid = orgDid;
	}

	public ILoginfo(Integer useDid, String logip, Date lastuse, String client, int orgDid) {
		this.useDid = useDid;
		this.logip = logip;
		this.lastuse = lastuse;
		this.client = client;
		this.orgDid = orgDid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "use_did")
	public Integer getUseDid() {
		return this.useDid;
	}

	public void setUseDid(Integer useDid) {
		this.useDid = useDid;
	}

	@Column(name = "logip", length = 25)
	public String getLogip() {
		return this.logip;
	}

	public void setLogip(String logip) {
		this.logip = logip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastuse", length = 19)
	public Date getLastuse() {
		return this.lastuse;
	}

	public void setLastuse(Date lastuse) {
		this.lastuse = lastuse;
	}

	@Column(name = "client", length = 25)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "org_did", nullable = false)
	public int getOrgDid() {
		return this.orgDid;
	}

	public void setOrgDid(int orgDid) {
		this.orgDid = orgDid;
	}

}
