package com.ak.entity;
// Generated 2016-1-23 13:06:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ISellist generated by hbm2java
 */
@Entity
@Table(name = "i_sellist", catalog = "akdbs")
public class ISellist implements java.io.Serializable {

	private Integer did;
	private int fcode;
	private String fname;
	private int ftype;

	public ISellist() {
	}

	public ISellist(int fcode, String fname, int ftype) {
		this.fcode = fcode;
		this.fname = fname;
		this.ftype = ftype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "fcode", nullable = false)
	public int getFcode() {
		return this.fcode;
	}

	public void setFcode(int fcode) {
		this.fcode = fcode;
	}

	@Column(name = "fname", nullable = false, length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "ftype", nullable = false)
	public int getFtype() {
		return this.ftype;
	}

	public void setFtype(int ftype) {
		this.ftype = ftype;
	}

}
