package com.ak.entity;
// Generated 2015-8-26 10:44:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SDepart generated by hbm2java
 */
@Entity
@Table(name = "s_depart", catalog = "akdbs")
public class SDepart implements java.io.Serializable {

	private Integer did;
	private int orgDid;
	private String fname;
	private Integer ftype;
	private String bref;

	public SDepart() {
	}

	public SDepart(int orgDid) {
		this.orgDid = orgDid;
	}

	public SDepart(int orgDid, String fname, Integer ftype, String bref) {
		this.orgDid = orgDid;
		this.fname = fname;
		this.ftype = ftype;
		this.bref = bref;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "org_did", nullable = false)
	public int getOrgDid() {
		return this.orgDid;
	}

	public void setOrgDid(int orgDid) {
		this.orgDid = orgDid;
	}

	@Column(name = "fname", length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "ftype")
	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	@Column(name = "bref", length = 10)
	public String getBref() {
		return this.bref;
	}

	public void setBref(String bref) {
		this.bref = bref;
	}

}
