package com.ak.entity;
// Generated 2016-1-3 9:10:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SDepart generated by hbm2java
 */
@Entity
@Table(name = "s_depart", catalog = "akdbs")
public class SDepart implements java.io.Serializable {

	private Integer did;
	private String fname;
	private Integer ftype;
	private String bref;
	private Integer orgDid;

	public SDepart() {
	}

	public SDepart(String fname, Integer ftype, String bref, Integer orgDid) {
		this.fname = fname;
		this.ftype = ftype;
		this.bref = bref;
		this.orgDid = orgDid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "fname", length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "ftype")
	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	@Column(name = "bref", length = 10)
	public String getBref() {
		return this.bref;
	}

	public void setBref(String bref) {
		this.bref = bref;
	}

	@Column(name = "org_did")
	public Integer getOrgDid() {
		return this.orgDid;
	}

	public void setOrgDid(Integer orgDid) {
		this.orgDid = orgDid;
	}

}
