package com.ak.entity;
// Generated 2016-1-3 9:10:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SHuman generated by hbm2java
 */
@Entity
@Table(name = "s_human", catalog = "akdbs")
public class SHuman implements java.io.Serializable {

	private Integer did;
	private int depDid;
	private String fname;
	private String sex;
	private String depname;
	private Integer ftype;
	private Date borth;
	private Integer orgDid;

	public SHuman() {
	}

	public SHuman(int depDid) {
		this.depDid = depDid;
	}

	public SHuman(int depDid, String fname, String sex, String depname, Integer ftype, Date borth, Integer orgDid) {
		this.depDid = depDid;
		this.fname = fname;
		this.sex = sex;
		this.depname = depname;
		this.ftype = ftype;
		this.borth = borth;
		this.orgDid = orgDid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "dep_did", nullable = false)
	public int getDepDid() {
		return this.depDid;
	}

	public void setDepDid(int depDid) {
		this.depDid = depDid;
	}

	@Column(name = "fname", length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "sex", length = 6)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "depname", length = 40)
	public String getDepname() {
		return this.depname;
	}

	public void setDepname(String depname) {
		this.depname = depname;
	}

	@Column(name = "ftype")
	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "borth", length = 10)
	public Date getBorth() {
		return this.borth;
	}

	public void setBorth(Date borth) {
		this.borth = borth;
	}

	@Column(name = "org_did")
	public Integer getOrgDid() {
		return this.orgDid;
	}

	public void setOrgDid(Integer orgDid) {
		this.orgDid = orgDid;
	}

}
