package com.ak.entity;
// Generated 2016-1-3 9:10:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SModules generated by hbm2java
 */
@Entity
@Table(name = "s_modules", catalog = "akdbs")
public class SModules implements java.io.Serializable {

	private Integer did;
	private String fname;
	private String fcode;
	private String cname;
	private String parent;
	private Boolean isdetail;
	private Boolean sep;
	private String icon;
	private Boolean issys;

	public SModules() {
	}

	public SModules(String fname, String fcode, String cname, String parent, Boolean isdetail, Boolean sep, String icon,
			Boolean issys) {
		this.fname = fname;
		this.fcode = fcode;
		this.cname = cname;
		this.parent = parent;
		this.isdetail = isdetail;
		this.sep = sep;
		this.icon = icon;
		this.issys = issys;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "fname", length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "fcode", length = 40)
	public String getFcode() {
		return this.fcode;
	}

	public void setFcode(String fcode) {
		this.fcode = fcode;
	}

	@Column(name = "cname", length = 25)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "parent", length = 25)
	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	@Column(name = "isdetail")
	public Boolean getIsdetail() {
		return this.isdetail;
	}

	public void setIsdetail(Boolean isdetail) {
		this.isdetail = isdetail;
	}

	@Column(name = "sep")
	public Boolean getSep() {
		return this.sep;
	}

	public void setSep(Boolean sep) {
		this.sep = sep;
	}

	@Column(name = "icon", length = 25)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "issys")
	public Boolean getIssys() {
		return this.issys;
	}

	public void setIssys(Boolean issys) {
		this.issys = issys;
	}

}
