package com.ak.entity;
// Generated 2015-8-26 10:44:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SOrgs generated by hbm2java
 */
@Entity
@Table(name = "s_orgs", catalog = "akdbs")
public class SOrgs implements java.io.Serializable {

	private Integer did;
	private String fname;
	private String address;
	private Integer mobile;
	private String contact;
	private Integer bednum;
	private String tel;
	private String fax;
	private String bank;
	private String bankact;
	private String alipay;
	private Boolean validate;
	private String bref;

	public SOrgs() {
	}

	public SOrgs(String fname, String address, Integer mobile, String contact, Integer bednum, String tel, String fax,
			String bank, String bankact, String alipay, Boolean validate, String bref) {
		this.fname = fname;
		this.address = address;
		this.mobile = mobile;
		this.contact = contact;
		this.bednum = bednum;
		this.tel = tel;
		this.fax = fax;
		this.bank = bank;
		this.bankact = bankact;
		this.alipay = alipay;
		this.validate = validate;
		this.bref = bref;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "fname", length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "mobile")
	public Integer getMobile() {
		return this.mobile;
	}

	public void setMobile(Integer mobile) {
		this.mobile = mobile;
	}

	@Column(name = "contact", length = 10)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "bednum")
	public Integer getBednum() {
		return this.bednum;
	}

	public void setBednum(Integer bednum) {
		this.bednum = bednum;
	}

	@Column(name = "tel", length = 30)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "bank", length = 50)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "bankact", length = 50)
	public String getBankact() {
		return this.bankact;
	}

	public void setBankact(String bankact) {
		this.bankact = bankact;
	}

	@Column(name = "alipay", length = 32)
	public String getAlipay() {
		return this.alipay;
	}

	public void setAlipay(String alipay) {
		this.alipay = alipay;
	}

	@Column(name = "validate")
	public Boolean getValidate() {
		return this.validate;
	}

	public void setValidate(Boolean validate) {
		this.validate = validate;
	}

	@Column(name = "bref", length = 20)
	public String getBref() {
		return this.bref;
	}

	public void setBref(String bref) {
		this.bref = bref;
	}

}
