package com.ak.entity;
// Generated 2016-1-3 9:10:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SRolepower generated by hbm2java
 */
@Entity
@Table(name = "s_rolepower", catalog = "akdbs")
public class SRolepower implements java.io.Serializable {

	private Integer did;
	private int rolDid;
	private int modDid;

	public SRolepower() {
	}

	public SRolepower(int rolDid, int modDid) {
		this.rolDid = rolDid;
		this.modDid = modDid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "rol_did", nullable = false)
	public int getRolDid() {
		return this.rolDid;
	}

	public void setRolDid(int rolDid) {
		this.rolDid = rolDid;
	}

	@Column(name = "mod_did", nullable = false)
	public int getModDid() {
		return this.modDid;
	}

	public void setModDid(int modDid) {
		this.modDid = modDid;
	}

}
