package com.ak.entity;
// Generated 2016-1-3 9:10:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SUser generated by hbm2java
 */
@Entity
@Table(name = "s_user", catalog = "akdbs")
public class SUser implements java.io.Serializable {

	private Integer did;
	private int orgDid;
	private int humDid;
	private String fname;
	private String password;
	private String email;
	private Integer mobile;
	private String qq;
	private Date dob;
	private String bref;
	private Set<SRole> SRoles = new HashSet<SRole>(0);

	public SUser() {
	}

	public SUser(int orgDid, int humDid) {
		this.orgDid = orgDid;
		this.humDid = humDid;
	}

	public SUser(int orgDid, int humDid, String fname, String password, String email, Integer mobile, String qq,
			Date dob, String bref, Set<SRole> SRoles) {
		this.orgDid = orgDid;
		this.humDid = humDid;
		this.fname = fname;
		this.password = password;
		this.email = email;
		this.mobile = mobile;
		this.qq = qq;
		this.dob = dob;
		this.bref = bref;
		this.SRoles = SRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "did", unique = true, nullable = false)
	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	@Column(name = "org_did", nullable = false)
	public int getOrgDid() {
		return this.orgDid;
	}

	public void setOrgDid(int orgDid) {
		this.orgDid = orgDid;
	}

	@Column(name = "hum_did", nullable = false)
	public int getHumDid() {
		return this.humDid;
	}

	public void setHumDid(int humDid) {
		this.humDid = humDid;
	}

	@Column(name = "fname", length = 40)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile")
	public Integer getMobile() {
		return this.mobile;
	}

	public void setMobile(Integer mobile) {
		this.mobile = mobile;
	}

	@Column(name = "qq", length = 20)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "bref", length = 10)
	public String getBref() {
		return this.bref;
	}

	public void setBref(String bref) {
		this.bref = bref;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "SUser")
	public Set<SRole> getSRoles() {
		return this.SRoles;
	}

	public void setSRoles(Set<SRole> SRoles) {
		this.SRoles = SRoles;
	}

}
